/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;

public class AttributeValue extends Asn1OpenType {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_InformationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_InformationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "AttributeValue";
   }

   public AttributeValue () {
      super();
   }

   public AttributeValue (byte [] value_) {
      super (value_);
   }

   public AttributeValue (byte [] value_, int encoding) {
      super (value_, encoding);
   }

   public AttributeValue (char [] value_, int encoding) {
      super (value_, encoding);
   }

}
