/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;
import dk.alexandra.stormbird.cheque.asnobjects.Extensions;

public class SignedInfo_attestsTo extends Asn1Choice {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_AttestationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_AttestationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "CHOICE";
   }

   // Choice element identifier constants
   public final static byte _EXTENSIONS = 1;
   public final static byte _DATAOBJECT = 2;

   public SignedInfo_attestsTo () {
      super();
   }

   public SignedInfo_attestsTo (byte choiceId_, Asn1Type element_) {
      super();
      setElement (choiceId_, element_);
   }

   public String getElemName () {
      switch (choiceID) {
      case _EXTENSIONS: return "extensions";
      case _DATAOBJECT: return "dataObject";
      default: return "UNDEFINED";
      }
   }

   public void set_extensions (Extensions value) {
      setElement (_EXTENSIONS, value);
   }

   public void set_dataObject (DataObject value) {
      setElement (_DATAOBJECT, value);
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = implicitLength;

      // decode CHOICE

      Asn1Tag tag = new Asn1Tag ();
      buffer.mark (8);
      int len = buffer.decodeTagAndLength (tag);
      final int choiceLen = len;

      int offset = buffer.getByteCount(), declen;

      if (tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 3))
      {
         Extensions lextensions_;
         buffer.getContext().eventDispatcher.startElement("extensions", -1);

         lextensions_ = new Extensions();
         lextensions_.decode (buffer, true, len);

         buffer.getContext().eventDispatcher.endElement("extensions", -1);
         setElement (_EXTENSIONS, lextensions_);
      }
      else if (tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 4))
      {
         DataObject ldataObject_;
         buffer.getContext().eventDispatcher.startElement("dataObject", -1);

         ldataObject_ = new DataObject();
         ldataObject_.decode (buffer, true, len);

         buffer.getContext().eventDispatcher.endElement("dataObject", -1);
         setElement (_DATAOBJECT, ldataObject_);
      }
      else {
         throw new Asn1InvalidChoiceOptionException (buffer, tag);
      }

      declen = buffer.getByteCount() - offset;
      if (choiceLen != Asn1Status.INDEFLEN && choiceLen != declen)
         throw new Asn1InvalidLengthException();
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;
      switch (choiceID) {
      // encode extensions
      case _EXTENSIONS:
         Extensions lextensions_ = (Extensions) getElement();
         buffer.getContext().eventDispatcher.startElement("extensions", -1);

         len = lextensions_.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 3, len);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("extensions", -1);
         break;

      // encode dataObject
      case _DATAOBJECT:
         DataObject ldataObject_ = (DataObject) getElement();
         buffer.getContext().eventDispatcher.startElement("dataObject", -1);

         len = ldataObject_.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 4, len);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("dataObject", -1);
         break;

      default:
         throw new Asn1InvalidChoiceOptionException();
      }

      return _aal;
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (element != null) {
         element.print (_out, getElemName(), _level+1);
      }
      indent (_out, _level);
      _out.println ("}");
   }

}
