/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;
import dk.alexandra.stormbird.cheque.asnobjects.AlgorithmIdentifier;

public class SubjectPublicKeyInfoValue extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_AttestationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_AttestationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "SubjectPublicKeyInfoValue";
   }

   public AlgorithmIdentifier algorithm;
   public Asn1BitString subjectPublicKey;

   public SubjectPublicKeyInfoValue () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public SubjectPublicKeyInfoValue (
      AlgorithmIdentifier algorithm_,
      Asn1BitString subjectPublicKey_
   ) {
      super();
      algorithm = algorithm_;
      subjectPublicKey = subjectPublicKey_;
   }

   public void init () {
      algorithm = null;
      subjectPublicKey = null;
   }

   public int getElementCount() { return 2; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return algorithm;
         case 1: return subjectPublicKey;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "algorithm";
         case 1: return "subjectPublicKey";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode algorithm

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("algorithm", -1);

         this.algorithm = new AlgorithmIdentifier();
         this.algorithm.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("algorithm", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "algorithm");

      // decode subjectPublicKey

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 3, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("subjectPublicKey", -1);

         this.subjectPublicKey = new Asn1BitString();
         this.subjectPublicKey.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("subjectPublicKey", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "subjectPublicKey");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 3))  {
            throw new Asn1UnexpectedElementException();
         }

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode subjectPublicKey

      if (this.subjectPublicKey != null) {
         buffer.getContext().eventDispatcher.startElement("subjectPublicKey", -1);

         len = this.subjectPublicKey.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("subjectPublicKey", -1);
      }
      else throw new Asn1MissingRequiredException ("subjectPublicKey");

      // encode algorithm

      if (this.algorithm != null) {
         buffer.getContext().eventDispatcher.startElement("algorithm", -1);

         len = this.algorithm.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("algorithm", -1);
      }
      else throw new Asn1MissingRequiredException ("algorithm");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (algorithm != null) algorithm.print (_out, "algorithm", _level+1);
      if (subjectPublicKey != null) subjectPublicKey.print (_out, "subjectPublicKey", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }

}
