/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 03-Jul-2020.
 */
package dk.alexandra.stormbird.cheque;

import com.objsys.asn1j.runtime.*;

public class Cheque extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_SignedChequeRtkey._rtkey);
      Asn1Type._setLicLocation(_SignedChequeRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Cheque";
   }

   public Asn1Integer amount;
   public Asn1OctetString riddle;

   public Cheque () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Cheque (
      Asn1Integer amount_,
      Asn1OctetString riddle_
   ) {
      super();
      amount = amount_;
      riddle = riddle_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public Cheque (long amount_,
      byte[] riddle_
   ) {
      super();
      amount = new Asn1Integer (amount_);
      riddle = new Asn1OctetString (riddle_);
   }

   public void init () {
      amount = null;
      riddle = null;
   }

   public int getElementCount() { return 2; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return amount;
         case 1: return riddle;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "amount";
         case 1: return "riddle";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode amount

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 2, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("amount", -1);

         this.amount = new Asn1Integer();
         this.amount.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("amount", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "amount");

      // decode riddle

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 4, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("riddle", -1);

         this.riddle = new Asn1OctetString();
         this.riddle.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("riddle", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "riddle");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 2) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 4))  {
            throw new Asn1UnexpectedElementException();
         }

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode riddle

      if (this.riddle != null) {
         buffer.getContext().eventDispatcher.startElement("riddle", -1);

         len = this.riddle.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("riddle", -1);
      }
      else throw new Asn1MissingRequiredException ("riddle");

      // encode amount

      if (this.amount != null) {
         buffer.getContext().eventDispatcher.startElement("amount", -1);

         len = this.amount.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("amount", -1);
      }
      else throw new Asn1MissingRequiredException ("amount");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (amount != null) amount.print (_out, "amount", _level+1);
      if (riddle != null) riddle.print (_out, "riddle", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }

}
