AttestationFramework

DEFINITIONS ::=
BEGIN


   SubjectPublicKeyInfo  ::=  SEQUENCE  {
     algorithm            AlgorithmIdentifier,
     subjectPublicKey     BIT STRING  }

   SmartContract ::= INTEGER

END
