RedeemCheque

DEFINITIONS ::=
BEGIN

IMPORTS
    SignedCheque
        FROM SignedCheque;

RedeemCheque ::= SEQUENCE {
    signedCheque         SignedCheque,
    attestation          X509Certificate,
    proof                Proof,
    signatureValue       BIT STRING 
}
		

Proof ::= SEQUENCE {
    base                 OCTET STRING,
    riddle               OCTET STRING,
    challengePoint       OCTET STRING,
    reponseValue         OCTET STRING 
}
		

END