/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;

public class AttributeType extends Asn1ObjectIdentifier {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_InformationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_InformationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "AttributeType";
   }

   public AttributeType () {
      super();
   }

   public AttributeType (int[] value_) {
      super (value_);
   }

}
