/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;

public class Extensions extends Asn1SeqOf {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_AuthenticationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_AuthenticationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Extensions";
   }

   public Extension[] elements;

   public Extensions () {
      elements = null;
   }

   /**
    * This constructor initializes the internal array to hold the 
    * given number of elements.  The element values must be manually 
    * populated.
    */
   public Extensions (int numRecords) {
      elements = new Extension [numRecords];
   }

   /**
    * This constructor initializes the internal array to hold the 
    * given the array.  
    */
   public Extensions (Extension[] elements_) {
      elements = elements_;
   }

   /** Returns the number of elements in the SEQUENCE OF. */
   public int getLength() {
      return elements.length;
   }

   public Asn1Type[] getElementValues() { return elements; }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      // decode SEQUENCE OF or SET OF

      java.util.LinkedList<Extension> llist =
         new java.util.LinkedList<Extension>();
      Asn1BerDecodeContext _context =
          new Asn1BerDecodeContext (buffer, llen);
      Extension element;
      int elemLen = 0;
      int i = 0;

      while (!_context.expired()) {
         buffer.getContext().eventDispatcher.startElement("elements", i++);

         element = new Extension();
         element.decode (buffer, true, elemLen);

         buffer.getContext().eventDispatcher.endElement("elements", i);
         llist.add (element);
      }

      elements = new Extension [llist.size()];
      llist.toArray (elements);

   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode SEQUENCE OF or SET OF

      for (int i = elements.length - 1; i >= 0; i--) {
         buffer.getContext().eventDispatcher.startElement("elements[" + i + "]", -1);

         len = this.elements[i].encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("elements[" + i + "]", -1);
      }

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      if (elements != null) {
         for (int i = 0; i < elements.length; i++) {
            String name = _varName + " [" + i + "]";
            elements[i].print (_out, name, _level);
         }
      }
   }

}
