/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.4.2, Date: 22-Jul-2020.
 */
package dk.alexandra.stormbird.cheque.asnobjects;

import com.objsys.asn1j.runtime.*;

public class SmartContract extends Asn1Integer {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_AttestationFrameworkRtkey._rtkey);
      Asn1Type._setLicLocation(_AttestationFrameworkRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "SmartContract";
   }

   public SmartContract () {
      super();
   }

   public SmartContract (long value_) {
      super (value_);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " = " + toString());
   }

}
