/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.3.4, Date: 25-Nov-2019.
 */
package id.attestation.shankai;

import com.objsys.asn1j.runtime.*;
import java.util.*;

public class Reader {

   public static void main (String args[])
   {
      String filename = new String ("message.dat");
      boolean trace = true;
      // Process command line arguments
      if (args.length > 0) {
         for (int i = 0; i < args.length; i++) {
            if (args[i].equals ("-v"))
               Diag.instance().setEnabled (true);
            else if (args[i].equals ("-i")) 
               filename = new String (args[++i]);
            else if (args[i].equals ("-notrace")) trace = false;
            else {
               System.out.println("usage: Reader [ -v ] [ -i <filename>");
               System.out.println("   -v  verbose mode: print trace info");
               System.out.println("   -i <filename>  " +
                                   "read encoded msg from <filename>");
               System.out.println("   -notrace  do not display trace info");
               System.exit(1);
            }
         }
      }

      Exception exception = null;
      Attestation value = null;
      try {
         // Create an input file stream object
         java.io.FileInputStream ins = new java.io.FileInputStream (filename);

         // Create a decode buffer object
         Asn1BerDecodeBuffer decodeBuffer = 
            new Asn1BerDecodeBuffer (ins);
         // Read and decode the message
         value = new Attestation ();
         value.decode (decodeBuffer);
      }
      catch (Exception e) {
         exception = e;
      }
      if (trace) {
         if ( exception == null ) System.out.println("Decode was successful");
         else System.out.println("Decode failed");
         if ( value != null )  {
            value.print (System.out, exception == null ? "value" : "partial value", 0);
         }
      }

      Asn1Util.closeRuntime();

      if ( exception != null ) {
         System.out.println (exception.getMessage());
         exception.printStackTrace();
         System.exit(1);
      }
   }
}
