name: "java-p1"

on: [workflow_call]

jobs:
  java-p1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"
      - name: build
        run: |
          ./gradlew --no-daemon build
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          junit_files: "build/test-results/**/*.xml"
      - name: grype
        uses: anchore/scan-action@v3
        with:
          path: build/libs/
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: java-build
          path: |
            build/libs/
            build/test-results/
            build/reports/
