name: "java-p1"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "ethereum/**"
      - "src/main/javascript/crypto/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "ethereum/**"
      - "src/main/javascript/crypto/**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"
      - name: shadowJar & check
        run: |
          ./gradlew --no-daemon check shadowJar
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: success() || failure()
        with:
          files: "build/test-results/**/*.xml"
      - name: grype
        uses: anchore/scan-action@v3
        with:
          path: build/libs/
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: java-build
          path: |
            build/libs/
            build/test-results/
            build/reports/
            ls -alF --color

  trigge-js-p1:
    needs:
      - pipeline
    uses: ./.github/workflows/js-p1.yml
