name: "js-p1"

on:
  push:
    branches:
      - main
    paths:
      - "src/main/javascript/crypto/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/main/javascript/crypto/**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"
      - name: build
        run: |
          cd src/main/javascript/crypto/
          npm i
          npm run build
      - name: prepare test
        run: |
          ./gradlew test
      - name: test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: src/main/javascript/crypto/
          test-script: npm run testjest
      - name: audit
        run: |
          cd src/main/javascript/crypto/
          npm audit
