/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.3.4, Date: 19-Nov-2019.
 */
package id.attestation;

import com.objsys.asn1j.runtime.*;

public class Attestation extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_TICKET_ATTESTATIONRtkey._rtkey);
      Asn1Type._setLicLocation(_TICKET_ATTESTATIONRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "Attestation";
   }

   public SignedInfo signedInfo;
   public AlgorithmIdentifier signatureAlgorithm;
   public Asn1BitString signatureValue;

   public Attestation () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Attestation (
      SignedInfo signedInfo_,
      AlgorithmIdentifier signatureAlgorithm_,
      Asn1BitString signatureValue_
   ) {
      super();
      signedInfo = signedInfo_;
      signatureAlgorithm = signatureAlgorithm_;
      signatureValue = signatureValue_;
   }

   public void init () {
      signedInfo = null;
      signatureAlgorithm = null;
      signatureValue = null;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return signedInfo;
         case 1: return signatureAlgorithm;
         case 2: return signatureValue;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "signedInfo";
         case 1: return "signatureAlgorithm";
         case 2: return "signatureValue";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode signedInfo

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("signedInfo", -1);

         signedInfo = new SignedInfo();
         signedInfo.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("signedInfo", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "signedInfo");

      // decode signatureAlgorithm

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("signatureAlgorithm", -1);

         signatureAlgorithm = new AlgorithmIdentifier();
         signatureAlgorithm.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("signatureAlgorithm", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "signatureAlgorithm");

      // decode signatureValue

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 3, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("signatureValue", -1);

         signatureValue = new Asn1BitString();
         signatureValue.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("signatureValue", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "signatureValue");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 3))  {
            throw new Asn1UnexpectedElementException();
         }

      }
      if (explicit && llen == Asn1Status.INDEFLEN) {
         matchTag (buffer, Asn1Tag.EOC);
      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode signatureValue

      if (signatureValue != null) {
         buffer.getContext().eventDispatcher.startElement("signatureValue", -1);

         len = signatureValue.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("signatureValue", -1);
      }
      else throw new Asn1MissingRequiredException ("signatureValue");

      // encode signatureAlgorithm

      if (signatureAlgorithm != null) {
         buffer.getContext().eventDispatcher.startElement("signatureAlgorithm", -1);

         len = signatureAlgorithm.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("signatureAlgorithm", -1);
      }
      else throw new Asn1MissingRequiredException ("signatureAlgorithm");

      // encode signedInfo

      if (signedInfo != null) {
         buffer.getContext().eventDispatcher.startElement("signedInfo", -1);

         len = signedInfo.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("signedInfo", -1);
      }
      else throw new Asn1MissingRequiredException ("signedInfo");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void decode( Asn1JsonDecodeBuffer buffer ) throws java.io.IOException
   {
      init();
      /* decode as JSON object */
      boolean[] elementKeysPresent_ = new boolean[3];
      buffer.readCharacter('{');
      if ( buffer.nextCharacterIsNot('}') ) {
         String current_json_identifier;
         for(;;)  {
            current_json_identifier = buffer.readString();
            buffer.readCharacter(':');
            if (current_json_identifier.equals("signedInfo") ) {
               if ( elementKeysPresent_[0] ){
                  throw new Asn1SetDuplicateException("signedInfo");
               }
               elementKeysPresent_[0] = true;
               signedInfo = new SignedInfo();
               signedInfo.decode(buffer);
            }
            else if (current_json_identifier.equals("signatureAlgorithm") ) {
               if ( elementKeysPresent_[1] ){
                  throw new Asn1SetDuplicateException("signatureAlgorithm");
               }
               elementKeysPresent_[1] = true;
               signatureAlgorithm = new AlgorithmIdentifier();
               signatureAlgorithm.decode(buffer);
            }
            else if (current_json_identifier.equals("signatureValue") ) {
               if ( elementKeysPresent_[2] ){
                  throw new Asn1SetDuplicateException("signatureValue");
               }
               elementKeysPresent_[2] = true;
               signatureValue = new Asn1BitString();
               signatureValue.decode(buffer);
            }
            else  {
               throw new Asn1Exception("unexpected elem: " + current_json_identifier);
            }

            if (buffer.nextCharacterIs(',')) {
               buffer.readCharacter(',');
               // loop around for next element
            }
            else break; //no more elems to decode

         }
      }
      buffer.readCharacter('}');
      if (signedInfo == null) {
         throw new Asn1MissingRequiredException("signedInfo");
      }
      if (signatureAlgorithm == null) {
         throw new Asn1MissingRequiredException("signatureAlgorithm");
      }
      if (signatureValue == null) {
         throw new Asn1MissingRequiredException("signatureValue");
      }
   }


   public void encode( Asn1JsonOutputStream outstream ) throws java.io.IOException
   {
      outstream.write('{');
      outstream.incrLevel();
      outstream.indent();
      /* encode signedInfo */
      if (signedInfo == null) {
         throw new Asn1MissingRequiredException("signedInfo");
      }
      outstream.write('"');
      outstream.write("signedInfo");
      outstream.write("\":");
      signedInfo.encode(outstream);

      /* encode signatureAlgorithm */
      if (signatureAlgorithm == null) {
         throw new Asn1MissingRequiredException("signatureAlgorithm");
      }
      outstream.write(',');
      outstream.indent();
      outstream.write('"');
      outstream.write("signatureAlgorithm");
      outstream.write("\":");
      signatureAlgorithm.encode(outstream);

      /* encode signatureValue */
      if (signatureValue == null) {
         throw new Asn1MissingRequiredException("signatureValue");
      }
      outstream.write(',');
      outstream.indent();
      outstream.write('"');
      outstream.write("signatureValue");
      outstream.write("\":");
      signatureValue.encode(outstream);

      outstream.decrLevel();
      outstream.indent();
      outstream.write('}');
   }


}
