/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.3.4, Date: 19-Nov-2019.
 */
package id.attestation;

import com.objsys.asn1j.runtime.*;

public class AttributeTypeAndValue extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      _setKey (_TICKET_ATTESTATIONRtkey._rtkey);
      Asn1Type._setLicLocation(_TICKET_ATTESTATIONRtkey._licLocation);
   }

   public String getAsn1TypeName()  {
      return "AttributeTypeAndValue";
   }

   public AttributeType type;
   public AttributeValue value;

   public AttributeTypeAndValue () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public AttributeTypeAndValue (
      AttributeType type_,
      AttributeValue value_
   ) {
      super();
      type = type_;
      value = value_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public AttributeTypeAndValue (int[] type_,
      AttributeValue value_
   ) {
      super();
      type = new AttributeType (type_);
      value = value_;
   }

   public void init () {
      type = null;
      value = null;
   }

   public int getElementCount() { return 2; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return type;
         case 1: return value;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "type";
         case 1: return "value";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode type

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 6, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("type", -1);

         type = new AttributeType();
         type.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("type", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "type");

      // decode value

      if (!_context.expired()) {
         buffer.getContext().eventDispatcher.startElement("value", -1);

         value = new AttributeValue();
         value.decode (buffer, true, 0);

         buffer.getContext().eventDispatcher.endElement("value", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "value");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 6))  {
            throw new Asn1UnexpectedElementException();
         }

      }
      if (explicit && llen == Asn1Status.INDEFLEN) {
         matchTag (buffer, Asn1Tag.EOC);
      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode value

      if (value != null) {
         buffer.getContext().eventDispatcher.startElement("value", -1);

         len = value.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("value", -1);
      }
      else throw new Asn1MissingRequiredException ("value");

      // encode type

      if (type != null) {
         buffer.getContext().eventDispatcher.startElement("type", -1);

         len = type.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("type", -1);
      }
      else throw new Asn1MissingRequiredException ("type");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void decode( Asn1JsonDecodeBuffer buffer ) throws java.io.IOException
   {
      init();
      /* decode as JSON object */
      boolean[] elementKeysPresent_ = new boolean[2];
      buffer.readCharacter('{');
      if ( buffer.nextCharacterIsNot('}') ) {
         String current_json_identifier;
         for(;;)  {
            current_json_identifier = buffer.readString();
            buffer.readCharacter(':');
            if (current_json_identifier.equals("type") ) {
               if ( elementKeysPresent_[0] ){
                  throw new Asn1SetDuplicateException("type");
               }
               elementKeysPresent_[0] = true;
               type = new AttributeType();
               type.decode(buffer);
            }
            else if (current_json_identifier.equals("value") ) {
               if ( elementKeysPresent_[1] ){
                  throw new Asn1SetDuplicateException("value");
               }
               elementKeysPresent_[1] = true;
               value = new AttributeValue();
               value.decode(buffer);
            }
            else  {
               throw new Asn1Exception("unexpected elem: " + current_json_identifier);
            }

            if (buffer.nextCharacterIs(',')) {
               buffer.readCharacter(',');
               // loop around for next element
            }
            else break; //no more elems to decode

         }
      }
      buffer.readCharacter('}');
      if (type == null) {
         throw new Asn1MissingRequiredException("type");
      }
      if (value == null) {
         throw new Asn1MissingRequiredException("value");
      }
   }


   public void encode( Asn1JsonOutputStream outstream ) throws java.io.IOException
   {
      outstream.write('{');
      outstream.incrLevel();
      outstream.indent();
      /* encode type */
      if (type == null) {
         throw new Asn1MissingRequiredException("type");
      }
      outstream.write('"');
      outstream.write("type");
      outstream.write("\":");
      type.encode(outstream);

      /* encode value */
      if (value == null) {
         throw new Asn1MissingRequiredException("value");
      }
      outstream.write(',');
      outstream.indent();
      outstream.write('"');
      outstream.write("value");
      outstream.write("\":");
      value.encode(outstream);

      outstream.decrLevel();
      outstream.indent();
      outstream.write('}');
   }


}
