/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.3.4, Date: 19-Nov-2019.
 */
package id.attestation;

import com.objsys.asn1j.runtime.*;
import java.util.*;

public class Writer {

   /* PDU: TICKET_ATTESTATION.Attestation */
   public static void main(String args[]) {

      String filename = new String ("message.json");
      boolean trace = true;
      
      if (args.length > 0) {
         for (int i = 0; i < args.length; i++) {
            if (args[i].equals ("-v"))
               Diag.instance().setEnabled (true);
            else if (args[i].equals ("-o"))
               filename = new String (args[++i]);
            else if (args[i].equals ("-notrace")) trace = false;
            else {
               System.out.println("usage: Writer [-v] [-o <filename>]");
               System.out.println("   -v  verbose mode: print trace info");
               System.out.println("   -o <filename>  " +
                                          "write encoded msg to <filename>");
               System.out.println("   -notrace  do not display trace info");
               System.exit(1);
            }
         }
      }
      
      // Create an encoding stream
      Asn1JsonOutputStream encodeStream = null;
      try {
         encodeStream = new Asn1JsonOutputStream (new java.io.OutputStreamWriter( new java.io.FileOutputStream(filename), "UTF-8") );
         id.attestation.Attestation attestation;
         attestation = new id.attestation.Attestation();

         attestation.signedInfo = new SignedInfo();

         attestation.signedInfo.version = new Version(0);

         attestation.signedInfo.serialNumber = new CertificateSerialNumber(0);

         attestation.signedInfo.signature = new AlgorithmIdentifier(4);

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signedInfo.signature.elements[0] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signedInfo.signature.elements[1] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signedInfo.signature.elements[2] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signedInfo.signature.elements[3] = new Asn1ObjectIdentifier(oidData);
         }

         attestation.signedInfo.issuer = new Name();
         {
            RDNSequence obj1;
            obj1 = new RDNSequence(0);

            attestation.signedInfo.issuer.setElement(Name._RDNSEQUENCE, obj1);
         }

         attestation.signedInfo.validity = new Validity();

         attestation.signedInfo.validity.notBefore = new Time();
         {
            Asn1GeneralizedTime obj2;
            obj2 = new Asn1GeneralizedTime("00800303050702");
            attestation.signedInfo.validity.notBefore.setElement(Time._GENERALTIME, obj2);
         }

         attestation.signedInfo.validity.notAfter = new Time();
         {
            Asn1UTCTime obj3;
            obj3 = new Asn1UTCTime("801028023212");
            attestation.signedInfo.validity.notAfter.setElement(Time._UTCTIME, obj3);
         }

         attestation.signedInfo.subject = new Name();
         {
            RDNSequence obj4;
            obj4 = new RDNSequence(0);

            attestation.signedInfo.subject.setElement(Name._RDNSEQUENCE, obj4);
         }

         attestation.signedInfo.subjectPublicKeyInfo = new SubjectPublicKeyInfo();

         attestation.signedInfo.subjectPublicKeyInfo.algorithm = new AlgorithmIdentifier(0);

         attestation.signedInfo.subjectPublicKeyInfo.subjectPublicKey = new Asn1BitString("'01'B");

         attestation.signedInfo.dataObject = new TicketDataObject();

         attestation.signedInfo.dataObject.match = new Asn1Integer(1L);

         attestation.signedInfo.dataObject.class_ = TicketDataObject_class_.lounge();

         attestation.signedInfo.dataObject.admission = new Asn1Integer(0);

         attestation.signatureAlgorithm = new AlgorithmIdentifier(5);

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signatureAlgorithm.elements[0] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signatureAlgorithm.elements[1] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signatureAlgorithm.elements[2] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signatureAlgorithm.elements[3] = new Asn1ObjectIdentifier(oidData);
         }

         {
            int[] oidData = {
               0, 1, 2, 3, 4
            };
            attestation.signatureAlgorithm.elements[4] = new Asn1ObjectIdentifier(oidData);
         }

         attestation.signatureValue = new Asn1BitString("'000100110111'B");
         attestation.encode (encodeStream);
         if (trace) {
            System.out.println("Encoding was successful");
         }
      }
      catch (Exception e) {
         System.out.println(e.getMessage());
         e.printStackTrace();
         System.exit(1);
      }
      finally {
         try {
            if (encodeStream != null) encodeStream.close ();
         }
         catch (Exception e) {
         }
         Asn1Util.closeRuntime();
      }
   }
}
